spring:
  application:
    name: service-zuul-server
    
server:
 port: 8090
 
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
 

zuul:
 routes:
 
  store:
   service-id: service-store
   path: /api/tienda/**
   
  cellphones:
   service-id: service-cellphones
   path: /api/phone/**
   
  users:
   service-id: service-commons-users
   path: /api/us/**
   
  oauth:
   service-id: service-oauth
   path: /api/security/**
   sensitive-headers: Cookie, Set-Cookie
   
  

   
ribbon:
 ConnectTimeout: 60000
 ReadTimeout: 60000

hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      TimeoutInMiliseconds: 60000
      
 